replicaCount: 1

image:
  registry: ghcr.io/mlflow-oidc
  name: oidc-provider-mock
  tag: latest

static:
  index: /usr/local/lib/python3.13/site-packages/oidc_provider_mock/templates/index.html
  authorization_form: /usr/local/lib/python3.13/site-packages/oidc_provider_mock/templates/authorization_form.html

config:
  users: {}
    # - username: alice@example.com
    #   name: Alice
    #   groups:
    #     - mlflow-users
    #     - experiments-reader
    #     - prompts-reader
    #     - models-reader
    # - username: bob@example.com
    #   name: Bob
    #   groups:
    #     - mlflow-users
    #     - experiments-editor
    #     - prompts-editor
    #     - models-editor
    # - username: charlie@example.com
    #   name: Charlie
    #   groups:
    #     - mlflow-users
    #     - experiments-manager
    #     - prompts-manager
    #     - models-manager
    # - username: dave@example.com
    #   name: Dave
    #   groups:
    #     - mlflow-users
    #     - experiments-no-access
    #     - prompts-no-access
    #     - models-no-access
    # - username: eve@example.com
    #   name: Eve
    #   groups:
    #     - mlflow-users
    # - username: frank@example.com
    #   name: Frank
    #   groups:
    #     - mlflow-admin
